# docker-compose.yml
version: "3"
services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
      - "9229:9229"
  db:
    image: postgres:10.5-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres      
    ports:
     - "5433:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
