# docker-compose.yml
version: "3"
services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
      - "9229:9229"
  db:
    image: postgres:11.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: qe-system   
    ports:
     - "5433:5432"
